### PR TITLE
made the rng working with the browser

### PR DESCRIPTION
**Pull request by AlexDM0**
the browser does not have a global variable

### CODE REVIEW

**Comment by defunctzombie** [comment]
The browser does have this field if you package with webpack or browserify.

I prefer using `global` since it is clearer to me over `window` which is just a magic global in browsers.

**Comment by AlexDM0** [comment]
Hi,

We do use browserify in vis.js and it still crashed on that line. Maybe that was caused by 6to5. I'd imagine better safe than sorry? But it's your project :)

Cheers

**Comment by defunctzombie** [comment]
Strange but I think maybe report to 6to5 project. They will get more
mileage out of supporting the global word than every node module patching.
If they are not receptive and the problem is not fixed another way, then we
can revisit. I prefer to push fixes upstream to the source but if that
doesn't happen we can patch around it.

**Comment by ssube** [comment]
@defunctzombie A webpack bundle only has `global` if you've kept the defaults. I work on a number of projects with `global: false` in the webpack conf, to discourage using it in browser-friendly code, which in turn breaks this library. 

I'm currently looking whether we can change that setting, but providing some function where we can override/replace the `global` would be super helpful (for testing and non-default bundles).

**Comment by defunctzombie** [comment]
@ssube gotcha, strange but ok. `global` is pretty explicit over window IMO. Also, this check for global is flawed since if window is undefined it will lead to a runtime error accessing `window`. Checks like this typically use `typeof window`

**Pull request closed without merging**
